version: 2

updates:
  # Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: "develop"
    
    # Grouping strategy for related updates
    groups:
      # Kotlin ecosystem
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.kotlinx*"
      
      # Compose Multiplatform
      compose:
        patterns:
          - "org.jetbrains.compose*"
          - "androidx.compose*"
      
      # Android ecosystem
      android:
        patterns:
          - "com.android*"
          - "androidx.*"
      
      # Koin dependency injection
      koin:
        patterns:
          - "io.insert-koin*"
      
      # Ktor networking
      ktor:
        patterns:
          - "io.ktor*"
      
      # Testing frameworks
      testing:
        patterns:
          - "*junit*"
          - "io.kotest*"
          - "io.mockk*"
          - "app.cash.turbine*"
      
      # Detekt and code quality
      code-quality:
        patterns:
          - "io.gitlab.arturbosch.detekt*"
          - "org.jlleitschuh.gradle.ktlint*"
    
    # Reviewers and assignees
    reviewers:
      - "YOUR_USERNAME"
      - "ANDROID_TEAM_MEMBER"
    assignees:
      - "YOUR_USERNAME"
    
    # Labels
    labels:
      - "dependencies"
      - "gradle"
      - "automated"
    
    # Commit message preferences
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    
    # Allow both direct and indirect updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    
    # Ignore specific dependencies that require manual updates
    ignore:
      # Ignore alpha/beta versions for production dependencies
      - dependency-name: "*"
        versions: ["< 1.0"]
      
      # Major version updates that need careful consideration
      - dependency-name: "org.jetbrains.kotlin*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-major"]
      
      # Dependencies that are managed elsewhere or have special requirements
      # - dependency-name: "specific-package-to-ignore"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    
    reviewers:
      - "YOUR_USERNAME"
      - "DEVOPS_TEAM_MEMBER"
    assignees:
      - "YOUR_USERNAME"
    
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "automated"
    
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker (if using Docker in the project)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    target-branch: "develop"
    
    reviewers:
      - "YOUR_USERNAME"
      - "DEVOPS_TEAM_MEMBER"
    assignees:
      - "YOUR_USERNAME"
    
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    
    commit-message:
      prefix: "docker"
      include: "scope"

  # NPM (if using Node.js tools)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    target-branch: "develop"
    
    # Group all npm dev dependencies together
    groups:
      npm-dev:
        dependency-type: "development"
        patterns:
          - "*"
    
    reviewers:
      - "YOUR_USERNAME"
    assignees:
      - "YOUR_USERNAME"
    
    labels:
      - "dependencies"
      - "npm"
      - "automated"
    
    commit-message:
      prefix: "npm"
      include: "scope"
    
    # Only update devDependencies for tools
    allow:
      - dependency-type: "development"

# Additional configuration notes:
# 
# 1. Replace placeholder usernames:
#    - YOUR_USERNAME: Your GitHub username
#    - ANDROID_TEAM_MEMBER: Android team member username
#    - DEVOPS_TEAM_MEMBER: DevOps team member username
# 
# 2. Adjust schedules based on your team's workflow
# 
# 3. Consider enabling security updates:
#    Add to any ecosystem block:
#    security-updates:
#      enabled: true
# 
# 4. For private repositories with npm/yarn:
#    Add registries configuration if needed
# 
# 5. Target branch strategy:
#    - Use "develop" for feature development
#    - Use "main" for hotfixes only
#    - Adjust based on your branching strategy
# 
# 6. Custom ignore patterns:
#    Add specific dependencies to ignore list
#    that require manual updates or testing