version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    
  - package-ecosystem: "gradle"
    directory: "/mobile"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"