platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!

  # MapLibre Native iOS SDK - required at link time by maplibre-compose KMP library
  pod 'MapLibre', '~> 6.8'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
